# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.3
env:
  global:
    - WORKSPACE=Cobra.xcworkspace
    - SDK=iphonesimulator9.3
    - DESTINATION="OS=9.3,name=iPhone 6S"
    - SCHEME="Cobra"
script:
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild -workspace $WORKSPACE -scheme $SCHEME -sdk $SDK -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO clean test
notifications:
  email:
    on_success: never

